// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/root/Desktop/projects/fortend/ts/mine-ui/node_modules/dumi/dist/client/theme-api/index.js';
