// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/root/Desktop/projects/fortend/ts/mine-ui/node_modules/dumi/theme-default/slots/Content/index.js';
